// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Vaja3.Models;
using System;

namespace Vaja3.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RAIN_MVC_dotnetCore_Primer.Models.Novica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();
                    b.Property<string>("avtor");

                    b.Property<string>("naziv");

                    b.Property<string>("besedilo");
                    b.Property<string>("datum");

                    b.HasKey("id");

                    b.ToTable("Novica");
                });

            modelBuilder.Entity("RAIN_MVC_dotnetCore_Primer.Models.Racun", b =>
            {
                b.Property<string>("upime");

                b.Property<string>("geslo");

                b.Property<string>("vrsta");

                b.HasKey("upime");

                b.ToTable("Racun");
            });
#pragma warning restore 612, 618
        }
    }
}
